version: '3.2'

networks:
  networkandi:
    driver: bridge

services:
  aplikasi:
    image: php-apache:1.0
    container_name: aplikasiandi
    ports:
      - '9000:9000'
    networks:
      - networkandi

  db:
    image: mysql:8.0
    container_name: mysql_andi
    restart: always
    volumes:
      - ./db/:/var/lib/mysql
    ports:
      - '6603:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root

  aplikasi1:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '80:80'
    environment:
      PMA_HOST: db
